---
name: Audio-Extract-PCM
version: 0.01
author:
  - 'Christoph Bussenius <pepe@cpan.org>'
abstract: Extract PCM data from audio files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::CaptureOutput: 1.10
build_requires:
  Compress::Zlib: 0
  Test::More: 0
provides:
  Audio::Extract::PCM:
    file: lib/Audio/Extract/PCM.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
